[options]
; This is the Odoo config file
addons_path = /mnt/extra-addons
admin_passwd = admin

db_host = turntable.proxy.rlwy.net
db_port = 39017
db_user = odoo_user
db_password = shuwafF2016
db_name = hospital_management

log_level = info
xmlrpc_port = 8069
