[options]
; This is the Odoo config file
addons_path = /mnt/extra-addons
admin_passwd = admin

db_host = postgres.railway.internal  ; Use internal Railway host for PostgreSQL
db_port = ${PGPORT}  ; PostgreSQL port (via environment variable)
db_user = ${PGUSER}  ; PostgreSQL user (via environment variable)
db_password = ${PGPASSWORD}  ; PostgreSQL password (via environment variable)
db_name = ${PGDATABASE}  ; PostgreSQL database (via environment variable)

log_level = info
xmlrpc_port = 8069
